config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: "frontend#index"
  get '/about', to: 'about#index'

  resources :pending_invite

  resources :profiles do
    resources :projects do
        resources :issues do
          resources :comments
        end
        resources :admin
    end
  end
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :profile
  has_many :comments
  validates :content, presence: true

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  define_method :new do
    @profile_names = []
    @project = Project.find params[:project_id]
    @project.profiles. each do |p|
      @profile_names << p.user_name
    end
    @issue = Issue.new
  end

  define_method :show do
    @project = Project.find params[:project_id]
    @issue = Issue.find params[:id]
  end

  define_method :update do
    @issue = Issue.find params[:id]
    if params[:commit] == "Transfer"
      @profile = Profile.find(params[:issue][:profile_id])
      @issue.profile_id = @profile.id
      if @issue.save
        redirect_to profile_project_path(current_user, Project.find(params[:project_id]), "success" + @profile.id.to_s)
        return
      end
    elsif params[:commit] == "Destroy"
      @issue.destroy
    elsif params[:commit] == "Convert"
      @issue.issue_type = params[:issue][:issue_type]
      if @issue.save
        redirect_to profile_project_path(current_user, Project.find(params[:project_id]))
        return
      end
    elsif params[:commit] == "Edit"
      @issue.content = params[:issue][:content]
      if @issue.save
        redirect_to profile_project_path(current_user, Project.find(params[:project_id]))
        return
      end
    else
      @issue.severity = params[:issue][:severity]
      @profile = Profile.find(params[:profile_id])

      if @issue.save
        redirect_to profile_project_path(current_user, Project.find(params[:project_id]))
        return
      end
    end
    redirect_to profile_project_path(current_user, Project.find(params[:project_id]))
  end

  define_method :edit do
    issue = Issue.find params[:id]
    project = Project.find(params[:project_id])
    if issue.status == "Open"
      issue.status = "Closed"
      issue.profile_id = project.admin_id
      redirect_to profile_project_path(current_user.profile, project)
    else
      issue.status = "Open"
      redirect_to profile_project_issue_path(current_user.profile, project, issue)
    end
    issue.save
  end

  define_method :create do
    youtube_links = ""
    imgur_links = ""
    params.each do |p|
      if p[0].include? "youtubes"
        youtube_links += "[+]" + p[1]
      elsif p[0].include? "imgurs"
        imgur_links += "[+]" + p[1]
      end
    end
    @project = Project.find(params[:project_id])
    @issue = @project.issues.new( issues_params )
    @issue.profile_id = current_user.profile.id
    @issue.resources = youtube_links + "(+)" + imgur_links
    @issue.project_id = @project.id
    @issue.content = ( params[:content_bug].length > 0 ) ? params[:content_bug] : params[:content_task]
    @issue.status = "Open"
    @issue.author_id = current_user.profile.id
    if @issue.save
      redirect_to profile_project_path(current_user.profile, @project)
    else
      render :new
    end
  end

  private
  define_method :issues_params do
    params.require(:issue).permit( :issue_type, :severity )
  end
end

app/views/issues/_issueframe.html.erb
<%= link_to profile_project_issue_path(current_user.profile, @project, object), class: "issueFrame" do %>
  <% if object.severity == "Very Important" %>
    <div class="issue_form_very_important">
      <h3><%= strip_tags( ApplicationHelper::limit_chars( object.content, 115 ).html_safe ) %></h3>
      <div class="">
        <h5 style="text-align:right;">Author: <%= Profile.find(object.author_id).user_name %> </h5>
        <h5 style="text-align:right;">Issue: <%= object.id %> </h5>
        <h5 style="text-align:right;">Created: <%= ApplicationHelper::convert_to_readable_time(object.created_at) %></h5>
      </div>
    </div>
  <%elsif object.severity == "Important" %>
    <div class="issue_form_important">
      <h3><%= strip_tags( ApplicationHelper::limit_chars( object.content, 115 ) ) %></h3>
      <div class="">
        <h5 style="text-align:right;">Author: <%= Profile.find(object.author_id).user_name %> </h5>
        <h5 style="text-align:right;">Issue: <%= object.id %> </h5>
        <h5 style="text-align:right;">Created: <%= ApplicationHelper::convert_to_readable_time(object.created_at) %></h5>
      </div>
    </div>
  <%elsif object.severity == "Not Important" %>
    <div class="issue_form_not_important">
      <h3><%= strip_tags( ApplicationHelper::limit_chars( object.content, 115 ) ) %></h3>
      <div class="">
        <h5 style="text-align:right;">Author: <%= Profile.find(object.author_id).user_name %> </h5>
        <h5 style="text-align:right;">Issue: <%= object.id %> </h5>
        <h5 style="text-align:right;">Created: <%= ApplicationHelper::convert_to_readable_time(object.created_at) %></h5>
      </div>
    </div>
  <%end%>
<%end%>

app/views/issues/new.html.erb
<%= render "layouts/errors", object: @issue %>

<div class="col-xs-8 col-xs-offset-2 form">
  <h1>New Issue</h1>
  <%= form_for [current_user.profile,@project,@issue] do |f| %>
    <div style="text-align:right;">
      <%= f.select :issue_type, ['Bug', 'Task'], { }, class: "issueType" %>
      <%= f.select :severity, ['Very Important', 'Important', 'Not Important'], { }, class: "issueType" %>
      <%= f.select :profile_id, @project.profiles.all.collect{ |p| [p.user_name, p.id ] }, { }, class: "issueType" %>

    </div>
    <%= f.label :content, class: "label label-default" %> <br>
    <div class="bugdesc">
      <textarea name="content_bug" class="formarea", placeholder="A bug contains the following five main parts:

1. Summary line (short, sweet, summation of the problem)
2. The Actual Result (a description of what happened; the problem)
3. The Expected Result (what you thought should happen instead of the problem)
4. Steps to Replicate (how someone else can make the problem happen too)

Make sure to select the severity and user this bug should go to above, in the dropdowns.

Use the input fields below to link any images or video links.

(You can write HTML in here.)" ></textarea> <br>
    </div>
    <div class="taskdesc" hidden>
      <textarea class="formarea", name="content_task" placeholder="Tasks should be as descriptive as they need to be. Try to give the person who will be working on the task as much information as possible to complete the task to the quality you are looking for.

Use outside resources to give more information, such as concept art, videos, examples, or screenshots.

Make sure to select the severity and user this task should go to above, in the dropdowns.

Use the input fields below to link any images or video links.

(You can write HTML in here.)" ></textarea> <br>
    </div>
    <div class="youtubes">
      <div class="youtubediv">
        <input type="text" name="youtubes" style="margin:0px;width:75%;" placeholder="www.youtube.com/linkaddress">
        <button type="button" class="btn-small-round btn btn-primary" id="youtubes" name="button">+</button>
      </div>
    </div>
    <div class="imgurs">
      <div class="imgurdiv">
        <input type="text" name="imgurs" style="margin:0px;width:75%;" placeholder="www.imgur.com/linkaddress">
        <button type="button" class="btn-small-round btn btn-primary" id="imgurs" name="button">+</button>
      </div>
    </div>
    <div style="text-align:right;">
      <%= f.submit "Create", class: "btn btn-primary" %>
    </div>
  <%end%>
</div>

app/views/issues/show.html.erb
<a href="" class="back-to-top"></a>

<div class="col-xs-8 col-xs-offset-2">
  <h2>[<%= @issue.issue_type %>] <%= ApplicationHelper::limit_chars( @issue.content, 35 ).html_safe %></h2>
  <% if @issue.severity == "Very Important" %>
    <h3><span class='label label-danger'><%= @issue.severity %></span></h3>
  <% elsif @issue.severity == "Important" %>
    <h3><span class='label label-warning'><%= @issue.severity %></span></h3>
  <% else %>
    <h3><span class='label label-success'><%= @issue.severity %></span></h3>
  <%end%>

  <% if @issue.status == "Open" %>
    <h5 style="display:inline;margin:0;"><span class='label label-primary'><%= @issue.status %></span></h5>
    <%= link_to "Close", edit_profile_project_issue_path( current_user.profile, @project, @issue ), class: "label label-danger", id: "closeIssue", data: { confirm: "This will remove the bug from its current owner and place it with the admin. Are you sure?"}%>
  <% elsif @issue.status == "Closed" %>
    <h5 style="display:inline;margin:0;"><span class='label label-danger'><%= @issue.status %></span></h5>
    <%= link_to "Open", edit_profile_project_issue_path( current_user.profile, @project, @issue ), class: "label label-primary", id: "openIssue", data: {confirm: "Are you sure?" } %>
  <%end%>
  <hr>
  <div class="col-xs-8">
    <h4>Content</h4>
    <div class="well" style="margin-top:12px;">
      <p><%= @issue.content.html_safe %></p>
      <% links = ApplicationHelper::convert_resources_to_links( @issue.resources ) %>
      <% links[0].each do |youtubes|  %>
        <% if ApplicationHelper::valid_youtube?( youtubes ) %>
        <div class="scalable scalable-16-9">
          <div class="scalable-content">
            <iframe src="<%= youtubes %>"></iframe>
          </div>
        </div>
        <%end%>
      <% end %>
      <% links[1].each do |imgur| %>
        <% if ApplicationHelper::valid_imgur?( imgur ) %>
          <a href="<%= imgur %>" style="margin-left: 7%;" target="_blank">
            <img src="<%= imgur %>" width="40%" max-width="40%" />
          </a>
        <%end%>
      <%end%>
    </div>
    <hr>
    <h5 style="text-align:right;">Created At:</h5>
    <h5 style="text-align:right;"><%= ApplicationHelper::convert_to_readable_time( @issue.created_at ) %></h5>
    <div style="text-align:right">
      <% if is_admin?(current_user, @project) %>
        <%= form_for [current_user.profile, @project, @issue] do |f| %>
          <%= f.submit "Delete", class: "btn btn-danger", data: {confirm: "This is permanent. Are you sure this Isssue has no use in the future?"} %>
        <% end %>
      <%end%>
    </div>
  </div>
  <div class="col-xs-4">
    <div class="row" style="margin-left:1%; margin-top:12px;" id="commentForm">
      <hr>
      <a href="#" class="commentLink">> Comment</a>
      <div class="issueComments" hidden>
        <% @issue.comments.sort_by(&:created_at).reverse.each do |comment| %>
          <div class="commentframe">
            <p><%= comment.content.html_safe %></p>
            <h6 style="text-align:right;">Author: <%= Profile.find(comment.author_id).user_name %></h6>
            <h6 style="text-align:right;">Posted On: <%= ApplicationHelper::convert_to_readable_time( comment.created_at ) %></h6>
          </div>
        <% end %>
        <div style="text-align:right;">
          <%= link_to "New", new_profile_project_issue_comment_path(current_user.profile, @project, @issue), class: "btn btn-primary" %>
        </div>
      </div>
      <hr>
    </div>
    <% if current_user.profile.id == @issue.profile_id || is_admin?(current_user, @project)%>
      <a href="#" class="updateLink" style="margin-left:1%; margin-top:12px;" id="updateLink">> Update</a>
      <div class="updateForm" hidden>
        <div style="text-align:right;">
          <%= form_for [current_user.profile, @project, @issue] do |f| %>
            <p> Update severity:
            <%= f.select :severity, ['Very Important', 'Important', 'Not Important'], { }, class: "issueType" %> </p>
            <%= f.submit "Update", class: "btn btn-primary" %>
          <%end%>
        </div>
      </div>
      <hr>
      <a href="#" class="transferLink" style="margin-left:1%; margin-top:12px;" id="transferLink">> Transfer</a>
      <div class="transferForm" hidden>
        <div style="text-align:right;">
          <% if is_admin?(current_user, @project) %>
            <p><b>Owned By: <%= Profile.find(@issue.profile_id).user_name %></b></p>
          <%end%>
          <%= form_for [current_user.profile, @project, @issue] do |f| %>
            <p> Transfer To:
            <%= f.select :profile_id, @project.profiles.all.collect{ |p| [p.user_name, p.id ] }, { }, class: "issueType" %> </p>
            <%= f.submit "Transfer", class: "btn btn-primary" %>
          <% end %>
          </p>
        </div>
      </div>
      <hr>
      <a href="#" class="convertLink" style="margin-left:1%; margin-top:12px;" id="convertLink">> Convert</a>
      <div class="convertForm" hidden>
        <div style="text-align:right;">
          <% if is_admin?(current_user, @project) %>
            <p><b>Owned By: <%= Profile.find(@issue.profile_id).user_name %></b></p>
          <%end%>
          <%= form_for [current_user.profile, @project, @issue] do |f| %>
            <p> Convert To:
            <% if @issue.issue_type == "Bug" %>
              <%= f.select :issue_type, ['Task'], { }, class: "issueType" %> </p>
            <%else%>
              <%= f.select :issue_type, ['Bug'], { }, class: "issueType" %> </p>
            <%end%>
            <%= f.submit "Convert", class: "btn btn-primary" %>
          <% end %>
          </p>
        </div>
      </div>
    <%end%>
    <hr>
    <a href="#" class="editLink" style="margin-left:1%; margin-top:12px;" id="editLink">> Edit</a>
    <div class="editForm" hidden>
      <%= form_for [current_user.profile, @project, @issue] do |f| %>
        <%= f.text_area :content, value: @issue.content, class: "formareaScalable", id: "formArea" %>
        <%= f.submit "Edit", class: "btn btn-primary right" %>
      <%end%>
    </div>
  </div>
</div>