config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: "frontend#index"
  get '/about', to: 'about#index'

  resources :pending_invite

  resources :profiles do
    resources :projects do
        resources :issues do
          resources :comments
        end
        resources :admin
    end
  end
end

app/views/admin/create.html.erb
<% if @sending_message.length > 0 %>
  <p class="alert alert-success"><strong><%= @sending_message %></strong></p>
<%else%>
  <p></p>
<%end%>

<div class="col-xs-4 col-xs-offset-5">
  <%= link_to profile_project_admin_index_path(current_user.profile, @project), class: 'projectHeader' do %>
    <h1>"Admin Panel"</h1>
  <%end%>
</div>

app/views/admin/index.html.erb
<div class="row">
  <% if @sending_error.length > 0 %>
    <p class="alert alert-danger"><strong><%= @sending_error %> </strong></p>
  <%else%>
    <p></p>
  <%end%>
</div>

<div class="row">
  <% if @sending_message.length > 0 %>
    <p class="alert alert-success"><strong><%= @sending_message %></strong></p>
  <%else%>
    <p></p>
  <%end%>
</div>

<div class="col-xs-2 col-xs-offset-1">
  <h5><a href="#" class="invitePanel">> Invite User</a></h5>
  <div class="row inviteForm">
    <div class="form" id="form">
      <div style="margin-left:5%;">
        <%= form_tag profile_project_admin_index_path(current_user.profile, @project) do %>
          <label class="label label-default">Email:</label><br>
          <input name="invite_address" width="100%" type="email" placeholder="friend@email.com"><br>
          <%= submit_tag "Send Invite", class: "btn btn-primary" %>
        <%end%>
      </div>
    </div>
  </div>
</div>

<div class="col-xs-5 col-xs-offset-2">
  <h5><a href="#" class="bugsPanel">> All Issues</a></h5>
    <div class="bugsForm">
      <table style="width:100%">
        <tr>
          <th>Issue</th>
          <th>Type</th>
          <th>Owner</th>
          <th>Severity</th>
          <th>Status</th>
        </tr>
        <% @issues.each do |issue| %>
          <tr>
            <% if issue.severity == "Very Important" %>
              <td><p><%= link_to ApplicationHelper::limit_chars( issue.content, 35 ), profile_project_issue_path( Profile.find(issue.profile_id), @project.id, issue ) %> </p> </td>

              <td class="">[<%= issue.issue_type %>]</td>

              <td class=""><b><%= Profile.find(issue.profile_id).user_name %></b></td>

              <td class="veryImportant">[<%= issue.severity %>]</td>

              <td><span class="<% if issue.status == 'Open' %> open <%else%> closed <%end%>"> <% if issue.status == 'Open' %> Open <%else%> Closed <%end%> </span></td>
            <% elsif issue.severity == "Important" %>
              <td><p><%= link_to ApplicationHelper::limit_chars( issue.content, 35 ), profile_project_issue_path( Profile.find(issue.profile_id), @project.id, issue ) %> </p> </td>

              <td class="">[<%= issue.issue_type %>]</td>

              <td class=""><b><%= Profile.find(issue.profile_id).user_name %></b></td>

              <td class="important">[<%= issue.severity %>]</td>

              <td><span class="<% if issue.status == 'Open' %> open <%else%> closed <%end%>"> <% if issue.status == 'Open' %> Open <%else%> Closed <%end%> </span></td>
            <% else %>
              <td><p><%= link_to ApplicationHelper::limit_chars( issue.content, 35 ), profile_project_issue_path( Profile.find(issue.profile_id), @project.id, issue ) %> </p> </td>

              <td class="">[<%= issue.issue_type %>]</td>

              <td class=""><b><%= Profile.find(issue.profile_id).user_name %></b></td>

              <td class="notImportant">[<%= issue.severity %>]</td>

              <td><span class="<% if issue.status == 'Open' %> open <%else%> closed <%end%>"> <% if issue.status == 'Open' %> Open <%else%> Closed <%end%> </span></td>
            <%end%>
          </tr>
        <%end%>
      </table>
    </div>
  </div>
</div>

<div class="row">

</div>