config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: "frontend#index"
  get '/about', to: 'about#index'

  resources :pending_invite

  resources :profiles do
    resources :projects do
        resources :issues do
          resources :comments
        end
        resources :admin
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true
  has_and_belongs_to_many :profiles
  has_many :pending_invites
  has_many :issues
  has_one :user
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  define_method :index do

  end

  define_method :show do
    @project = Project.find params[:id]
    @my_issues = @project.issues.where(profile_id: current_user.profile.id)
    @my_issues = ApplicationHelper::sort_issues_by_severity(@my_issues)

    if params[:format].class != NilClass
      profile_id = params[:format]
      if profile_id.include? "success"
        profile_id = profile_id.sub("success", "")
        flash.now[:notice] = "Successfully sent issue to: " + Profile.find(profile_id).user_name
      end
    end

  end

  define_method :new do
    @project = Project.new
  end

  define_method :create do
    @project = current_user.profile.projects.new project_params
    @project.admin_id = current_user.profile.id
    if @project.save
      current_user.profile.projects.push @project
      current_user.profile.save
      redirect_to profile_project_path( current_user, @project )
    else

    end
  end

  private
  define_method :project_params do
    params.require(:project).permit(:name, :admin_id)
  end
end

app/views/projects/index.html.erb
<div class="container">
  <div class="col-xs-10 col-xs-offset-1">
    <% @projects.each do |p| %>
      <div class="row project frame">
        <%= link_to profile_project_path(current_user.profile, p), class: "projectHeader" do %>
          <h1 style="text-align:center;"><%= p.name %></h1>
        <%end%>

        <% if is_admin?(current_user, p) %>
          <h6 class="danger-text" style="text-align:right;">Admin: You </h6>
        <%else%>
          <h6 class="danger-text" style="text-align:right;">Admin: <%= User.find( p.admin_id ).email %></h6>
        <%end%>
      </div>
    <%end%>
    <div class="" style="text-align:right">
      <%= link_to "Add New", new_profile_project_path(current_user.profile), class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container">
  <div class="col-xs-6 col-xs-offset-3">
    <div class="row form">
      <h1 style="text-align:center;">New Project</h1>
      <%= form_for [current_user.profile, @project] do |f| %>
        <%= f.label :name %> <br>
        <%= f.text_field :name, id: 'projectName' %> <br>
        <%= f.submit "Create", class: "btn btn-primary", style: "text-align:right;" %>
      <%end%>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<a href="" class="back-to-top"></a>


<div class="row">
  <div class="form">
    <div style="text-align:center;">
      <h1><%= @project.name %></h1>
    </div>
    <div style="text-align:right;margin-right:6%;">
      <% if is_admin?(current_user, @project)%>
        <%= link_to "Admin", profile_project_admin_index_path(current_user.profile, @project), id: "Admin", class: "btn btn-danger" %>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-7 col-xs-offset-1">
    <div class="row" style="margin-bottom:12px;">
      <button class="btn btn-lg btn-danger issuebutton" id="bugButton">Bugs</button>
      <button class="btn btn-lg btn-warning" id="taskButton">Tasks</button>
      <div style="float:right;margin-right:4%;">
        <%= link_to "Add Issue", new_profile_project_issue_path(current_user.profile, @project), class: "btn btn-primary", id: "newIssueButton" %>
      </div>
      <hr>

    </div>
    <% if ApplicationHelper::issue_of_count(@my_issues, "Bug") == 0 %>
      <div class="Bugs">
        <h3>No Bugs</h3>
      </div>
    <%end%>
    <%if ApplicationHelper::issue_of_count(@my_issues, "Task") == 0 %>
      <div class="Tasks" hidden>
        <h3>No Tasks</h3>
      </div>
    <%end%>
    <% @my_issues.each do |i| %>
      <% if i.status == "Open" %>
        <% if i.issue_type == "Bug" %>
          <div class="Bugs">
            <%= render "issues/issueframe", object: i %>
          </div>
        <% else %>
          <div class="Tasks" hidden>
            <%= render "issues/issueframe", object: i %>
          </div>
        <%end%>
      <%end%>
    <%end%>
  </div>
  <div class="row">
    <div class="col-xs-3 col-xs-offset-0">
      <h2><a href="#" class="projectUsersLink" style="margin-left:4%;">>Users</a></h2>
      <div class="projectUsers">
        <% @project.profiles.each do |pr| %>
          <p class="form">
            <% if is_admin?(User.find(pr.user_id), @project) %>
              <span class="danger-text">[Admin]</span> <%=User.find(pr.user_id).email%> (<%= pr.user_name %>)
            <%else%>
              <%=User.find(pr.user_id).email%> (<%= pr.user_name %>)
            <%end%>
          </p>
        <%end%>
      </div>
    </div>
  </div>
</div>