config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: "frontend#index"
  get '/about', to: 'about#index'

  resources :pending_invite

  resources :profiles do
    resources :projects do
        resources :issues do
          resources :comments
        end
        resources :admin
    end
  end
end

app/models/pending_invite.rb
class PendingInvite < ActiveRecord::Base
  belongs_to :project
  validates :invite_email, presence: true
  validates :invite_email, presence: true
end

app/controllers/pending_invite_controller.rb
class PendingInviteController < ApplicationController
  define_method :index do
    @pending = PendingInvite.all.where( invite_email: current_user.email )
  end

  define_method :edit do
    pending_invite = PendingInvite.find(params[:id])
    pending_project = Project.find(pending_invite.project_id)
    if params[:format] == "join"
      pending_invite.destroy
      pending_invite.save
      current_user.profile.projects << pending_project
    end
    redirect_to profile_project_path(current_user, pending_project)
  end

  define_method :destroy do
    ignored_project_invite = PendingInvite.find(params[:id])
    ignored_project_invite.destroy
    ignored_project_invite.save
    redirect_to root_path
  end
end

app/views/pending_invite/index.html.erb
<div class="col-xs-10 col-xs-offset-1">
  <div style="text-align:center;">
    <% if user_signed_in? %>
      <% @pending.each do |p| %>
        <div class="row">
            <p>You have an invite to join <b><%= Project.find(p.project_id).name %> </b>from: <b><%= p.invite_email %></b></p>
            <div style="">
              <%= link_to "Join", edit_pending_invite_path(p.id, "join"), class: "btn btn-primary", id: "joinPending" %>
              <%= link_to "Ignore", pending_invite_path(p.id), method: :delete, class: "btn btn-danger", id: "ignorePending" %>
            </div>
        </div>
      <%end%>
    <%end%>
  </div>
</div>